### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by thomasfmunozs** [PUC-IIC3141/2017-1#2]
Hola, quiero testear lo que he hecho, pero antes de modificar los archivos corrí ```CreateStudentDB.java```, por lo que hay datos que el sistema usa, pero con las modificaciones creo que no funcionará. Parece que no existe el comando ```DROP TABLE```, así que no sé que hacer.

EDIT: No puedo iniciar el servidor, probablemente porque busca la tabla creada, y ahora los métodos de acceso son distintos y van a otra dirección

**Comment by vdrg** [comment]
Borra el directorio donde está la base de datos, y después al correr el servidor te lo crea desde 0.

**Comment by thomasfmunozs** [comment]
Buena, funcionó. Gracias!
