### ISSUE TITLE
Vecinos en B+-Tree

### ISSUE THREAD

**Issue by vdrg** [PUC-IIC3141/2017-1#5]
Hola!

Una duda, para revisar si es posible la redistribución podemos simplemente probar con el/los vecinos más directos (con los que se "comparte" el mismo BTreeDir)?

Gracias!

**Comment by cirojas** [comment]
Podría ser que un vecino no comparta el mismo BTreeDir (si es que la hoja que va a hacer split es el primero o el último del BTreeDir). Pero buscar más allá les puede resultar muy complicado (encontrar el bloque es fácil ya que están ordenados, pero después hay que actualizar el directorio que apunta a ese bloque), así que no hay problemas si se limitan solo a buscar en los vecinos que comparten el BTreeDir.

**Comment by vdrg** [comment]
Perfecto, gracias!
